bikeax/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from ecom.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/$',dashboard, name="dashboard"),
    url(r'^dashboard/category/$',dashcategory, name="dashcategory"),
    url(r'^dashboard/product/$',dashproduct, name="dashproduct"),
    url(r'^dashboard/addcategory/$',addcategory, name="addcategory"),
    url(r'^dashboard/addproduct/$',addproduct, name="addproduct"),
    url(r'^product_del/(?P<pk>\d+)/', product_del, name='product_del'),
    url(r'^cato_del/(?P<pk>\d+)/', cato_del, name='cato_del'),
    url(r'^dashboard/sales/$', salesreport, name="sales"),
    url(r'^orderdet/(?P<pk>\d+)/', orderdet, name='orderdet'),
	url(r'^aboutus/$',aboutus,name="aboutus"),
	url(r'^privacy/$',privacy,name="privacy"),
	url(r'^terms/$',terms,name="terms"),
	url(r'^info/$',info,name="info"),
	

    url(r'^$',index ,name="index"),
    url(r'^checkout/(?P<pk>\d+)/$', checkout, name="checkout"),
    url(r'^category/(?P<pk>\d+)/', categoryview, name='category'),
    url(r'^search/',search, name="search"),
    url(r'^thankyou/',thankyou, name="thankyou"),
    url(r'^finalthnx/',finalthnx, name="finalthnx"),
    url(r'^user_detail/',user_detail, name="user_detail"),
    url(r'^product/(?P<pk>\d+)/', product_detail, name='product_detail'),

    url(r'^cart/$', cart_detail, name='cart_detail'),
    url(r'^cart/add/(?P<product_id>\d+)/$', cart_add, name='cart_add'),
    url(r'^cart/remove/(?P<product_id>\d+)/$', cart_remove, name='cart_remove'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecom/forms.py
from django import forms
from .models import Category, Product, CustomerDetail


class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = ("Name", "Description")


class ProductForm(forms.ModelForm):
	class Meta:
		model=Product
		fields=("Categories", "Name","Image","IDorSNO","Description","Price","NumbersAvailable")


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class CustomerDetailForm(forms.ModelForm):
	class Meta:
		model=CustomerDetail
		fields=("name", "phonenumber", "Email", "ShippingAddress", "City", "State", "Landmark", "Pincode",)

templates/frontend/aboutus.html
 
 <!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>Free Style A Ecommerce Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
<link href="{% static 'frontend/css/bootstrap.css' %}" rel="stylesheet"  type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'frontend/js/jquery-1.11.0.min.js' %}"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="{% static 'frontend/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Free Style Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100,300,400,500,700,800,900,100italic,300italic,400italic,500italic,700italic,800italic,900italic' rel='stylesheet' type='text/css' >
<link href='http://fonts.googleapis.com/css? family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
<!--//fonts-->
<script type="text/javascript" src="{% static 'frontend/js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'frontend/js/easing.js' %}"></script>
<script type="text/javascript">
					jQuery(document).ready(function($) {
						$(".scroll").click(function(event){
							event.preventDefault();
							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
						});
					});
				</script>
<!-- start menu -->
<script src="{% static 'frontend/js/simpleCart.min.js' %}"> </script>
<link href="{% static 'frontend/css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'frontend/js/memenu.js' %}"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>
</head>
<body>
	<!--top-header-->
	<div class="container">
		<div class="pull-right">
		{% if request.user.is_authenticated %}
			<p><a href="{% url 'auth_logout' %}" class="simpleCart_empty">LOGOUT</a></p>
        {% else %}
             <a class="active" href="{% url 'auth_login' %}">LOGIN</a>
             <a class="active" href="{% url 'registration_register' %}">REGISTER</a>
        {% endif %}
		</div>
	</div>
	<div class="top-header">
	<div class="container">
		<div class="top-header-main">
			<div class="col-md-4 top-header-left">
				<div class="search-bar">
				<form action="/search/" method="get">{% csrf_token %}

					<input type="text" name="q" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
					<input type="submit" value="">
					</form>
				</div>
			</div>
			<div class="col-md-4 top-header-middle">
				<a href="/"><img src="{% static 'frontend/images/logo.png' %}" alt="" /></a>
			</div>
			<div class="col-md-4 top-header-right">
				<div class="cart box_1">

					{% if cart|length > 0 %}
						<a href="{% url 'cart_detail' %}">
						<h3>
							<div class="total">
							<span class="total">${{ cart.get_total_price }}</span>
							(<span class="simpleCart">{{ cart|length }} items}</span>)
						</div>
							<img src="{% static 'frontend/images/cart-1.png' %}" alt="" />
						</a>
						<div class="clearfix"> </div>
						{% else %}
						Your cart is empty.

				{% endif %}

					</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--top-header-->
	<!--bottom-header-->
	<div class="header-bottom">
		<div class="container">
			<div class="top-nav">
				<ul class="memenu skyblue"><li class="active"><a href="/">Home</a></li>
				{% if categories %}
					{% for category in categories %}
					<li class="grid"><a href="{% url 'category' pk=category.pk %}">{{ category.Name }}</a></li>
					{% endfor %}
					{% endif %}

			<div class="clearfix"> </div>
		</div>
	</div>
 
	
	            <h4> About Us</h4>
	<p>Kreedsgears is an online store offering most popular Helmets, Bike Accessories, 
	Bike Care Products, Bike Parts under brand names like Vega, Studds, Steel Bird, Monster,
	Monster etc.Started in 2016, we've come a long, glorious way, and have been privileged to 
	work with a fantastic and ever growing brands.  A round the clock growing team, we're young, 
	constantly hungry, energetic (for the most part) and insanely fierce team with a heightened 
	sense of quirkiness and almost genius minds, whose sole purpose is to achieve highest level 
	of “customer satisfaction” by making you have an easy and quality shopping experience.</p> 

	



	<!--start-footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-top">
			<div class="col-md-3 footer-left">
					<h3><a href="/aboutus/">ABOUT US</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="/privacy/"> PRIVACY POLICY</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="/terms/">TERMS & CONDITIONS</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="/info/">DELIVERY INFORMATION</a></h3>
					
				</div>	
			</div>
		</div>
	</div>
	<!--end-footer-->
	<!--end-footer-text-->
	<div class="footer-text">
		<div class="container">
			<div class="footer-main">
				<p class="footer-class">© 2018 Style All Rights Reserved | Design by  <a href="http://techstackinnovations.com/" target="_blank">Techstack Innovations</a> </p>
			
			</div>
			<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
		</div>
		<script type="text/javascript">
									$(document).ready(function() {
										/*
										var defaults = {
								  			containerID: 'toTop', // fading element id
											containerHoverID: 'toTopHover', // fading element hover id
											scrollSpeed: 1200,
											easingType: 'linear'
								 		};
										*/

										$().UItoTop({ easingType: 'easeOutQuart' });

									});
								</script>

	</div>
	<!--end-footer-text-->
</body>
</html>

templates/frontend/category.html
<!--A Design by W3layouts 
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>Bikeax | Category</title>
<link href="{% static 'frontend/css/bootstrap.css' %}" rel="stylesheet"  type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'frontend/js/jquery-1.11.0.min.js' %}"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="{% static 'frontend/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Free Style Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100,300,400,500,700,800,900,100italic,300italic,400italic,500italic,700italic,800italic,900italic' rel='stylesheet' type='text/css' >
<link href='http://fonts.googleapis.com/css? family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
<!--//fonts-->
<script type="text/javascript" src="{% static 'frontend/js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'frontend/js/easing.js' %}"></script>
<script type="text/javascript">
					jQuery(document).ready(function($) {
						$(".scroll").click(function(event){		
							event.preventDefault();
							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
						});
					});
				</script>	
<!-- start menu -->
<script src="{% static 'frontend/js/simpleCart.min.js' %}"> </script>
<link href="{% static 'frontend/css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'frontend/js/memenu.js' %}"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>				
</head>
<body> 
	<!--top-header-->
	<div class="container">
		<div class="pull-right">
		{% if request.user.is_authenticated %}
			<p><a href="{% url 'auth_logout' %}" class="simpleCart_empty">LOGOUT</a></p>
        {% else %}
             <a class="active" href="{% url 'auth_login' %}">LOGIN</a>
             <a class="active" href="{% url 'registration_register' %}">REGISTER</a>
        {% endif %}
		</div>
	</div>
	<div class="top-header">
	<div class="container">
		<div class="top-header-main">
			<div class="col-md-4 top-header-left">
				<div class="search-bar">
				<form action="/search/" method="get">{% csrf_token %}

					<input type="text" name="q" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
					<input type="submit" value="">
					</form>
				</div>
			</div>
			<div class="col-md-4 top-header-middle">
				<a href="/"><img src="{% static 'frontend/images/logo.png' %}" alt="" /></a>
			</div>
			<div class="col-md-4 top-header-right">
				<div class="cart box_1">
				{% if cart|length > 0 %}
						<a href="{% url 'cart_detail' %}">
						<h3>
							<div class="total">
							<span class="total">₹{{ cart.get_total_price }}</span>
							<span class="simpleCart">{{ cart|length }} items</span>
						</div>
							<img src="{% static 'frontend/images/cart-1.png' %}" alt="" />
						</a>
						<div class="clearfix"> </div>
						{% else %}
						<img src="{% static 'frontend/images/cart-2.png' %}" alt="" />
						Your cart is empty.

				{% endif %}
						<div class="clearfix"> </div>
					</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--top-header-->
	<!--bottom-header-->
	<div class="header-bottom">
		<div class="container">
			<div class="top-nav">
				<ul class="memenu skyblue"><li class="active"><a href="/">Home</a></li>
				{% if categories %}
					{% for category in categories %}
					<li class="grid"><a href="{% url 'category' pk=category.pk %}">{{ category.Name }}</a></li>
					{% endfor %}
					{% endif %}
					
			<div class="clearfix"> </div>
		</div>
	</div>
	<!--bottom-header-->
	
	<div class="shoes"> 
		<div class="container"> 
			<div class="product-one">
				{% if products %}
					{% for product in products %}
				<div class="col-md-3 product-left"> 
					<div class="p-one simpleCart_shelfItem">
							
							<a href="{% url 'product_detail' pk=product.pk %}">
								{% if product.Image %}
									<img src="{{ product.Image.url }}" alt="" height="268" width="223" />
								{% endif %} 
								<div class="mask">
									<span>Quick View</span>
								</div>
							</a>
						<h4>{{ product.Name }} </h4>
						<p>
						<a class="item_add" href="{% url 'product_detail' pk=product.pk %}">
						<i></i> 
						<span class=" item_price">₹{{ product.Price }}</span></a></p>
				
					</div>
					</div>
					{% endfor %}
				{% endif %}
				
				<div class="clearfix"> </div>

			</div>
		</div>
	</div>
	<!--banner-starts-->
	<div class="bnr" id="home">
		<div  id="top" class="callbacks_container">
			<ul class="rslides" id="slider4">
			    <li>
					<div class="banner-1"></div>
				</li>
				<li>
					<div class="banner-2"></div>
				</li>
				<li>
					<div class="banner-3"></div>
				</li>
			</ul>
		</div>
		<div class="clearfix"> </div>
	</div>
	<!--banner-ends--> 
	<!--Slider-Starts-Here-->
				<script src="{% static 'frontend/js/responsiveslides.min.js' %}"></script>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: false,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
	
	<!--start-shoes--> 
	
	<!--start-footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-top">
				<div class="col-md-3 footer-left">
					<h3><a href="#ONPROCESSING">ABOUT US</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="#ONPROCESSING"> ACCOUNT</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="#ONPROCESSING">CUSTOMER SERVICES</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="#ONPROCESSING">CATEGORIES</a></h3>
					
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--end-footer-->
	<!--end-footer-text-->
	<div class="footer-text">
		<div class="container">
			<div class="footer-main">
				<p class="footer-class">© 2018 Style All Rights Reserved | Design by  <a href="http://techstackinnovations.com/" target="_blank">Techstack Innovations</a> </p>
			</div>
		</div>
		<script type="text/javascript">
									$(document).ready(function() {
										/*
										var defaults = {
								  			containerID: 'toTop', // fading element id
											containerHoverID: 'toTopHover', // fading element hover id
											scrollSpeed: 1200,
											easingType: 'linear' 
								 		};
										*/
										
										$().UItoTop({ easingType: 'easeOutQuart' });
										
									});
								</script>
		<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	</div>
	<!--end-footer-text-->	
</body>
</html>

templates/frontend/single.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html>
<head>
<title>Bikeax|Product Details</title>
<link href="{% static 'frontend/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'frontend/js/jquery-1.11.0.min.js' %}"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="{% static 'frontend/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'frontend/css/flexslider.css' %}" type="text/css" media="screen" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Free Style Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link href= 'http://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100,300,400,500,700,800,900,100italic,300italic,400italic,500italic,700italic,800italic,900italic' rel='stylesheet' type='text/css'>
<link href= 'http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
<!--//fonts-->
<script type="text/javascript" src="{% static 'frontend/js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'frontend/js/easing.js' %}"></script>
<script type="text/javascript">
					jQuery(document).ready(function($) {
						$(".scroll").click(function(event){
							event.preventDefault();
							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
						});
					});
				</script>
<!-- start menu -->
<script src="{% static 'frontend/js/simpleCart.min.js' %}"> </script>
<link href="{% static 'frontend/css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript"  src="{% static 'frontend/js/memenu.js' %}"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>
</head>
<body>
	<!--top-header-->
        <div class="container">
		<div class="pull-right">
		{% if request.user.is_authenticated %}
			<p><a href="{% url 'auth_logout' %}" class="simpleCart_empty">LOGOUT</a></p>
        {% else %}
             <a class="active" href="{% url 'auth_login' %}">LOGIN</a>
             <a class="active" href="{% url 'registration_register' %}">REGISTER</a>
        {% endif %}
		</div>
	</div>
	<div class="top-header">
	<div class="container">
		<div class="top-header-main">
			<div class="col-md-4 top-header-left">
				<div class="search-bar">
					<form action="/search/" method="get">{% csrf_token %}
			    		<input type="text" name="q" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
						<input type="submit" value="">
					</form>
				</div>
			</div>
			<div class="col-md-4 top-header-middle">
				<a href="/"><img src="{% static 'frontend/images/logo-4.png' %}" alt="" /></a>
			</div>
			<div class="col-md-4 top-header-right">
				<div class="cart box_1">

					{% if cart|length > 0 %}
						<a href="{% url 'cart_detail' %}">
						<h3>
							<div class="total">
							<span class="total">₹{{ cart.get_total_price }}</span>
							(<span class="simpleCart">{{ cart|length }} items}</span>)
						</div>
							<img src="{% static 'frontend/images/cart-1.png' %}" alt="" />
						</a>
						<div class="clearfix"> </div>
						{% else %}
						<img src="{% static 'frontend/images/cart-2.png' %}" alt="" />
						Your cart is empty.

				{% endif %}

					</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<div class="header-bottom">
		<div class="container">
			<div class="top-nav">
				<ul class="memenu skyblue"><li class="active"><a href="/">Home</a></li>
				{% if categories %}
					{% for category in categories %}
					<li class="grid"><a href="{% url 'category' pk=category.pk %}">{{ category.Name }}</a></li>
					{% endfor %}
					{% endif %}

			<div class="clearfix"> </div>
		</div>
	</div>

<!--top-header-->
<!--bottom-header-->
	<!--bottom-header-->
	<!--start-breadcrumbs-->
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="/">Home</a></li>
					<li class="active">Product Detail</li>
				</ol>
			</div>
		</div>
	</div>
	<!--end-breadcrumbs-->
	<!--start-single-->
	<div class="single contact">
		<div class="container">
			<div class="single-main">
				<div class="col-md-9 single-main-left">
				<div class="sngl-top">
					<div class="col-md-5 single-top-left">
						<div class="flexslider">
							<ul class="slides">
								<li data-thumb="{{ post.Image.url }}">
									<img src="{{ post.Image.url }}"/>
								</li>
								<li data-thumb="{{ post.Image.url }}">
									<img src="{{ post.Image.url }}" />
								</li>
								<li data-thumb="{{ post.Image.url }}">
									<img src="{{ post.Image.url }}"/>
								</li>
								<li data-thumb="{{ post.Image.url }}">
									<img src="{{ post.Image.url }}"/>
								</li>
							</ul>
						</div>
<!-- FlexSlider -->
  <script defer src="{% static 'frontend/js/jquery.flexslider.js' %}"></script>


	<script>
// Can also be used with $(document).ready()
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    controlNav: "thumbnails"
  });
});
</script>
				</div>
				<div class="col-md-7 single-top-right">
					<div class="details-left-info simpleCart_shelfItem">
						<h3>{{ post.Name }}</h3>
						<p class="availability">Availability: {% if post.NumbersAvailable %}<span style="color:green">In stock</span>{% else %}<span class="color">Out of stock</span>{% endif %}</p>
						<div class="price_single">
							<span class="reducedfrom">{{ post.Price }}</span>
							<span class="actual item_price">{{ post.Price }}</span>
						</div>
						<h2 class="quick">Description</h2>
						<p class="quick_desc"> {{ post.Description}}</p>
						<ul class="product-colors">
							<h3>available Colors ::</h3>
							<li><a class="color1" href="#"><span> </span></a></li>
							<li><a class="color2" href="#"><span> </span></a></li>
							<li><a class="color3" href="#"><span> </span></a></li>
							<li><a class="color4" href="#"><span> </span></a></li>
							<li><a class="color5" href="#"><span> </span></a></li>
							<li><a class="color6" href="#"><span> </span></a></li>
							<li><a class="color7" href="#"><span> </span></a></li>
							<li><a class="color8" href="#"><span> </span></a></li>
							<div class="clear"> </div>
						</ul>
						<ul class="size">
							<h3>Length</h3>
							<li><a href="#">7</a></li>
							<li><a href="#">6</a></li>
						</ul>


					<form action="{% url 'cart_add' post.id %}" method="post">
              			{% csrf_token %}
              		<div class="quantity_box">
										<label for="id_quantity">Quantity:</label>
										<select name="quantity" id="id_quantity">
										{% for i in range %}
										<option value="{{i}}">{{i}}</option>
										{% endfor %}
										</select>
              		{{ cart_product_form.update }}
              		</div>
              		<div class="single-but item_add">
             		<input type="submit" value="add to cart" class="btn btn-primary">
             		</div>
          </form>

					<div class="clearfix"> </div>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--end-single-->
	<!--start-footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-top">
			<div class="col-md-3 footer-left">
					<h3><a href="aboutus/">ABOUT US</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="privacy/"> PRIVACY POLICY</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="terms/">TERMS & CONDITIONS</a></h3>
					
				</div>
				<div class="col-md-3 footer-left">
					<h3><a href="info/">DELIVERY INFORMATION</a></h3>
					
				</div>	
			</div>
		</div>
	</div>
	<!--end-footer-->
	<!--end-footer-text-->
	<div class="footer-text">
		<div class="container">
			<div class="footer-main">
				<p class="footer-class">© 2018 Style All Rights Reserved | Design by  <a href="http://techstackinnovations.com/" target="_blank">Techstack Innovations</a> </p>
			</div>
		</div>
		<script type="text/javascript">
									$(document).ready(function() {
										/*
										var defaults = {
								  			containerID: 'toTop', // fading element id
											containerHoverID: 'toTopHover', // fading element hover id
											scrollSpeed: 1200,
											easingType: 'linear'
								 		};
										*/

										$().UItoTop({ easingType: 'easeOutQuart' });

									});
								</script>
		<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	</div>
	<!--end-footer-text-->
</body>
</html>

templates/frontend/thanku.html
{% extends 'frontend/index.html' %}

{% load static %}



{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 20%; margin-bottom: 20%;">
        <div align="center">
        	<h1> Thank you for shopping with us.</h1>  
        </div>
        </div>
    </div>
{% endblock %}